language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4
    - php: 8.0
    - php: 8.1

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -v